[metadata.heroku]
  root-package = "github.com/berfarah/beardroid"

[[constraint]]
  name = "github.com/botopolis/bot"
  version = "0.3.0"

[[constraint]]
  name = "github.com/botopolis/redis"
  version = "0.2.0"

[[constraint]]
  name = "github.com/botopolis/slack"
  version = "0.2.0"
