[metadata.heroku]
  root-package = "github.com/berfarah/beardroid"

[[constraint]]
  name = "github.com/berfarah/gobot"
  version = "0.1.0"

[[constraint]]
  name = "github.com/berfarah/gobot-store-redis"
  branch = "master"

[[constraint]]
  name = "github.com/berfarah/gobot-slack"
  branch = "master"
