[metadata.heroku]
  root-package = "github.com/berfarah/beardroid"

[[override]]
  name = "github.com/botopolis/bot"
  version = "0.4.2"

[[constraint]]
  name = "github.com/botopolis/redis"
  version = "0.2.0"

[[constraint]]
  name = "github.com/botopolis/slack"
  branch = "action"
